### ISSUE TITLE
Minor naming convention violations / minor Date format issue

### ISSUE THREAD

**Issue by mcjazzyfunky** [hanc2006/sl-datepicker#1]
@hanc2006 This is really a great and extremely useful piece of work and surely an important contribution to the Shoelace project👍... thank you sooooo much for this project.

Some minor issues:

1. I guess, for custom element property names should always be in camelCase, attribute names should always be in snake-case (at least in the Shoelace world).
The property names should always determine the attribute names.
That means: I think the attribute name of property "firstDayOfWeek" should be "first-day-of-week"

2. Regarding min-date, max-date, state-date etc.:
    Why using date format like 25-06-2021 and not the international ISO date format 2021-06-25???

**Comment by hanc2006** [comment]
Thanks for your support, I fixed the issues in the last two commits :+1:

**Comment by mcjazzyfunky** [comment]
@hanc2006 Sorry, Daniele, I've forgotten something: I guess the default locale should be "en-US" for all Shoelace components, so I think it would be better if the default value for "firstDayOfWeek" was 0 (= Sunday) instead of 1 (= Monday).
There are at least two places where "1" is to be found: Component property `firstDayOfWeek` and the `CalendarView` constructor.

**Comment by hanc2006** [comment]
Defaults values for locale and first day of week updated

**Comment by mcjazzyfunky** [comment]
Great, thanks.
So I can close this issue.
